### ISSUE TITLE
Creation of deploy-tag fails if local repo does not have the deployed commit

### ISSUE THREAD

**Issue by roback** [twingly/capistrano-twingly#18]
Capistrano creates the deploy tags on the local repo and then pushes the tags to the remote.

If the commit that should be deployed does not exist in the local repo, the deployment tag cannot be created, because the commit has cannot be found.

``` Shell
INFO[3b0edb0e] Running /usr/bin/env git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" on localhost
cap aborted!
SSHKit::Command::Failed: git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" exit status: 32768
git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" stdout: Nothing written
git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" stderr: fatal: Failed to resolve '4042f21' as a valid ref.
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:56:in `block in _execute'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:37:in `tap'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:37:in `_execute'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:26:in `execute'
/Users/mattias/.gem/ruby/2.1.2/bundler/gems/capistrano-twingly-782c50a2aae9/lib/capistrano/twingly/tasks/tag_deploy_in_git.rake:12:in `block (3 levels) in <top (required)>'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:14:in `instance_exec'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:14:in `run'
/Users/mattias/.gem/ruby/2.1.2/gems/sshkit-1.5.1/lib/sshkit/dsl.rb:10:in `run_locally'
/Users/mattias/.gem/ruby/2.1.2/bundler/gems/capistrano-twingly-782c50a2aae9/lib/capistrano/twingly/tasks/tag_deploy_in_git.rake:11:in `block (2 levels) in <top (required)>'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/dsl/task_enhancements.rb:12:in `block in after'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/dsl.rb:15:in `invoke'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/tasks/framework.rake:64:in `each'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/mattias/.gem/ruby/2.1.2/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/mattias/.gem/ruby/2.1.2/bin/cap:23:in `load'
/Users/mattias/.gem/ruby/2.1.2/bin/cap:23:in `<main>'
Tasks: TOP => deploy:push_deploy_tag
(See full trace by running task with --trace)
The deploy has failed with an error: #<SSHKit::Command::Failed: git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" exit status: 32768
git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" stdout: Nothing written
git tag 2014-06-03__13_21_16__production 4042f21 -m "Deployed by Mattias Roback <mattias.roback@twingly.com>" stderr: fatal: Failed to resolve '4042f21' as a valid ref.
```

**Comment by walro** [comment]
Me today
