### ISSUE TITLE
Strange SSHKit error

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#23]
````
$ bundle exec cap staging deploy:start
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host haldir.live.lkp.primelabs.se: undefined method `recv' for #<IO:fd 11>
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:65:in `fill'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:86:in `next_packet'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:210:in `block in wait'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `loop'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `wait'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:87:in `initialize'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `new'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `start'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `call'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `create_new_entry'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:22:in `checkout'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:179:in `with_ssh'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:82:in `upload!'
/Users/dentarg/.gem/ruby/2.1.5/bundler/gems/capistrano-twingly-68e53d27c953/lib/capistrano/twingly/tasks/upstart.rake:27:in `block (4 levels) in <top (required)>'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
NoMethodError: undefined method `recv' for #<IO:fd 11>
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:65:in `fill'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:86:in `next_packet'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:210:in `block in wait'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `loop'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `wait'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:87:in `initialize'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `new'
/Users/dentarg/.gem/ruby/2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `start'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `call'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:50:in `create_new_entry'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/connection_pool.rb:22:in `checkout'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:179:in `with_ssh'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:82:in `upload!'
/Users/dentarg/.gem/ruby/2.1.5/bundler/gems/capistrano-twingly-68e53d27c953/lib/capistrano/twingly/tasks/upstart.rake:27:in `block (4 levels) in <top (required)>'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/dentarg/.gem/ruby/2.1.5/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:export_upstart => deploy:foreman:upload_procfile
(See full trace by running task with --trace)
````

When I ran the command again, it worked as excepted.

I think this has something to do with me having the following in `~/.ssh/config`:

````
Host *.live.lkp.primelabs.se
    ProxyCommand ssh -W %h:%p azog.datacenter.tw.ly
````

(my SSH config is shared with other computers I use, where this is needed because I'm using them outside the office)

Logging this as one of many problems with Capistrano, so we can be aware of all troubles.

**Comment by walro** [comment]
Close and re-open if it occurs again? I don't think I have seen this.

**Comment by jage** [comment]
Yes, I haven't been able to reproduce this either. Flaky Internet tubes?
